version: '3'

services:
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: spore
            MYSQL_USER: spore
            MYSQL_PASSWORD: spore
        volumes:
            - ./db_uploads:/var/lib/mysql-files/
            - ./db_data:/var/lib/mysql
    web:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/usr/share/nginx/html

        links:
            - php-fpm
            - db
            - redis
    php-fpm:
        build: ./php-fpm
        ports:
            - "9000:9000"
        volumes:
            - ./src:/usr/share/nginx/html
    php-cli:
        build: ./php-cli
        links: 
            - db
    redis:
        image: redis:latest
        ports: 
            - "6379:6379"
    composer:
        image: composer:latest

    node:
        image: node:latest


